enum ActionTypes {
  CHANGE_USERNAME = 'boilerplate/Home/CHANGE_USERNAME',
  HOUSE_DATA_FETCH_SUCCEEDED = 'boilerplate/Home/HOUSE_DATA_FETCH_SUCCEEDED',
  HOUSE_DATA_FETCH_FAILED = 'boilerplate/Home/HOUSE_DATA_FETCH_FAILED',
  HOUSE_DATA_FETCH_REQUESTED = 'boilerplate/Home/HOUSE_DATA_FETCH_REQUESTED',
  CHARACTER_DATA_FETCH_REQUESTED = 'boilerplate/Home/CHARACTER_DATA_FETCH_REQUESTED',
  CHARACTER_DATA_FETCH_SUCCEEDED = 'boilerplate/Home/CHARACTER_DATA_FETCH_SUCCEEDED',
  CHARACTER_DATA_FETCH_FAILED = 'boilerplate/Home/CHARACTER_DATA_FETCH_FAILED',
  CHARACTER_RESET_DATA = 'boilerplate/Home/CHARACTER_RESET_DATA',
}

export default ActionTypes;
